require('dotenv').config();
const { sequelize, EmployeeShift } = require('./models');

async function main() {
  try {
    console.log('--- Aggregating July 2026 Shift Summaries into employee_shifts ---');
    await sequelize.query('DELETE FROM employee_shifts WHERE companyId = 1 AND month = 7 AND year = 2026;');

    const insertSql = `
      INSERT INTO employee_shifts (
        employeeId, companyId, shiftName, month, year,
        totalDays, presentDays, presentWithPermissionDays, absentDays, leaveDays,
        lateDays, earlyExitDays, totalWorkingHours, totalOvertimeHours,
        totalPermissionMinutes, firstSeenDate, lastSeenDate, createdAt, updatedAt
      )
      SELECT 
        employeeId,
        companyId,
        shiftName,
        7 AS month,
        2026 AS year,
        COUNT(*) AS totalDays,
        SUM(CASE WHEN status = 'Present' THEN 1 ELSE 0 END) AS presentDays,
        SUM(CASE WHEN status = 'Present with Permission' THEN 1 ELSE 0 END) AS presentWithPermissionDays,
        SUM(CASE WHEN status = 'Absent' THEN 1 ELSE 0 END) AS absentDays,
        SUM(CASE WHEN status = 'Leave' THEN 1 ELSE 0 END) AS leaveDays,
        SUM(CASE WHEN isLate = 1 THEN 1 ELSE 0 END) AS lateDays,
        SUM(CASE WHEN isEarlyExit = 1 THEN 1 ELSE 0 END) AS earlyExitDays,
        COALESCE(SUM(workingHours), 0) AS totalWorkingHours,
        COALESCE(SUM(overtimeHours), 0) AS totalOvertimeHours,
        COALESCE(SUM(permissionMinutes), 0) AS totalPermissionMinutes,
        MIN(attendanceDate) AS firstSeenDate,
        MAX(attendanceDate) AS lastSeenDate,
        NOW() AS createdAt,
        NOW() AS updatedAt
      FROM attendances
      WHERE companyId = 1 
        AND attendanceDate BETWEEN '2026-07-01' AND '2026-07-31'
        AND autoGenerated = false
        AND shiftName IS NOT NULL
        AND shiftName != ''
      GROUP BY employeeId, companyId, shiftName;
    `;

    await sequelize.query(insertSql);
    const count = await EmployeeShift.count({ where: { companyId: 1, month: 7, year: 2026 } });
    console.log(`✅ Successfully generated ${count} employee shift summary records for July 2026!`);
    process.exit(0);
  } catch (err) {
    console.error('❌ Error aggregating employee shifts:', err);
    process.exit(1);
  }
}

main();
