// ============================================================
// models/Attendance.js
// ============================================================
// IMPORTANT: shiftName / scheduledStartTime / scheduledEndTime
// are stored DIRECTLY on this table — NOT as a FK to any
// ShiftType table. The shift is auto-detected from punch time.
// ============================================================

module.exports = (sequelize, DataTypes) => {
  const Attendance = sequelize.define(
    "Attendance",
    {
      id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },

      employeeId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: { model: "employees", key: "id" },
      },
      companyId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: { model: "companies", key: "id" },
      },
      departmentId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        references: { model: "departments", key: "id" },
      },
      workedDeptId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        references: { model: "departments", key: "id" },
      },
      shiftId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        references: { model: "shift_types", key: "id" },
      },
      attendanceDate: {
        type: DataTypes.DATEONLY,
        allowNull: false,
      },

      // ── Shift info (stored inline, NO FK) ─────────────────
      // Auto-detected from first punch. Values: 'A' | 'B' | 'C' | 'Staff' | 'Unknown'
      shiftName: {
        type: DataTypes.STRING(20),
        allowNull: true,
        comment:
          "Auto-detected from punch-in time. A/B/C for workers, Staff for staff.",
      },
      scheduledStartTime: {
        type: DataTypes.STRING(8),
        allowNull: true,
        comment: "e.g. 08:30 — from SHIFT_WINDOWS config",
      },
      scheduledEndTime: {
        type: DataTypes.STRING(8),
        allowNull: true,
        comment: "e.g. 16:30 — from SHIFT_WINDOWS config",
      },

      // ── Punch times ───────────────────────────────────────
      firstCheckIn: { type: DataTypes.DATE, allowNull: true },
      lastCheckOut: { type: DataTypes.DATE, allowNull: true },
      totalCheckIns: { type: DataTypes.INTEGER, defaultValue: 0 },
      totalCheckOuts: { type: DataTypes.INTEGER, defaultValue: 0 },

      // ── Calculated ────────────────────────────────────────
      workingHours: { type: DataTypes.DECIMAL(5, 2), defaultValue: 0 },
      overtimeHours: { type: DataTypes.DECIMAL(5, 2), defaultValue: 0 },

      // ── Status ───────────────────────────────────────────
      status: {
        type: DataTypes.ENUM(
          "Present",
          "Present with Permission",
          "Absent",
          "Half Day",
          "Leave",
          "Holiday",
          "Week Off",
        ),
        allowNull: false,
        defaultValue: "Absent",
      },

      // ── Finalization flag ─────────────────────────────────
      // false = provisional (created by real-time punch webhook)
      // true  = final      (set by cron or manual admin regenerate)
      isFinalized: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        comment:
          "false = provisional (live dashboard). true = finalized by cron.",
      },

      // ── Late / early ──────────────────────────────────────
      isLate: { type: DataTypes.BOOLEAN, defaultValue: false },
      lateByMinutes: { type: DataTypes.INTEGER, defaultValue: 0 },
      isEarlyExit: { type: DataTypes.BOOLEAN, defaultValue: false },
      earlyExitMinutes: { type: DataTypes.INTEGER, defaultValue: 0 },

      // ── Permission (staff only) ───────────────────────────
      // Actual minutes deducted from the 120-min monthly pool.
      // Summing this column per employee per month gives pool usage.
      permissionMinutes: {
        type: DataTypes.INTEGER,
        defaultValue: 0,
        comment:
          "Minutes deducted from monthly 120-min pool (staff only). Sum per month = total used.",
      },

      // ── Flags ─────────────────────────────────────────────
      isHoliday: { type: DataTypes.BOOLEAN, defaultValue: false },
      isWeekOff: { type: DataTypes.BOOLEAN, defaultValue: false },
      autoGenerated: {
        type: DataTypes.BOOLEAN,
        defaultValue: true,
        comment:
          "true = cron/webhook generated. false = manually entered by HR.",
      },

      // ── Approval ──────────────────────────────────────────
      approvedBy: { type: DataTypes.INTEGER, allowNull: true },
      approvedAt: { type: DataTypes.DATE, allowNull: true },

      // ── Audit ─────────────────────────────────────────────
      remarks: { type: DataTypes.TEXT, allowNull: true },
      createdBy: { type: DataTypes.INTEGER, allowNull: true },
      updatedBy: { type: DataTypes.INTEGER, allowNull: true },
    },
    {
      tableName: "attendances",
      timestamps: true,
      indexes: [
        {
          unique: true,
          fields: ["employeeId", "attendanceDate"],
          name: "unique_employee_date",
        },
        { fields: ["companyId"] },
        { fields: ["attendanceDate"] },
        { fields: ["status"] },
        { fields: ["isFinalized"] },
      ],
    },
  );

  Attendance.associate = (models) => {
    Attendance.belongsTo(models.Employee, {
      foreignKey: "employeeId",
      as: "employee",
    });
    Attendance.belongsTo(models.Company, {
      foreignKey: "companyId",
      as: "company",
    });
    Attendance.belongsTo(models.Department, {
      foreignKey: "departmentId",
      as: "department",
    });
    Attendance.belongsTo(models.Department, {
      foreignKey: "workedDeptId",
      as: "workedDepartment",
    });
    Attendance.belongsTo(models.ShiftType, {
      foreignKey: "shiftId",
      as: "shiftType",
    });
  };

  return Attendance;
};
